#!/usr/bin/env node
/**
 * Installs a pre-commit hook that runs local lint/test/docs validations.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..", "..");
const GIT_DIR = path.join(REPO_ROOT, ".git");
const HOOKS_DIR = path.join(GIT_DIR, "hooks");
const HOOK_PATH = path.join(HOOKS_DIR, "pre-commit");
const MARKER = "# Keyboard Defense pre-commit hook";
const RUNNER_RELATIVE_PATH = "apps/keyboard-defense/scripts/hooks/runChecks.mjs";

function ensureGitRepo() {
  if (!fs.existsSync(GIT_DIR) || !fs.statSync(GIT_DIR).isDirectory()) {
    console.warn("[hooks] .git directory not found. Skipping hook installation.");
    process.exit(0);
  }
}

function ensureHooksDir() {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
}

export function buildHookContent() {
  const lines = [
    "#!/usr/bin/env bash",
    MARKER,
    "set -euo pipefail",
    "",
    'REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"',
    `HOOK_RUNNER="$REPO_ROOT/${RUNNER_RELATIVE_PATH}"`,
    "",
    'if [ ! -f "$HOOK_RUNNER" ]; then',
    '  echo "[hooks] runner not found at $HOOK_RUNNER"',
    "  exit 1",
    "fi",
    "",
    'export REPO_ROOT',
    'node "$HOOK_RUNNER" "$@"',
    ""
  ];
  return lines.join("\n");
}

function installHook() {
  const content = buildHookContent();
  if (fs.existsSync(HOOK_PATH)) {
    const existing = fs.readFileSync(HOOK_PATH, "utf8");
    if (!existing.includes(MARKER)) {
      console.warn(
        "[hooks] Existing pre-commit hook detected that was not generated by this script. Skipping overwrite."
      );
      return;
    }
  }
  fs.writeFileSync(HOOK_PATH, content, { mode: 0o755 });
  fs.chmodSync(HOOK_PATH, 0o755);
  console.log(`[hooks] Installed pre-commit hook at ${path.relative(REPO_ROOT, HOOK_PATH)}.`);
}

ensureGitRepo();
ensureHooksDir();
installHook();
