#!/usr/bin/env node
/**
 * Installs the repo's pre-commit hook so lint/test/docs commands run automatically.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..", "..", "..");
const GIT_DIR = path.join(REPO_ROOT, ".git");
const HOOKS_DIR = path.join(GIT_DIR, "hooks");
const HOOK_PATH = path.join(HOOKS_DIR, "pre-commit");
const MARKER = "# Keyboard Defense pre-commit hook";

function ensureGitRepo() {
  if (!fs.existsSync(GIT_DIR) || !fs.statSync(GIT_DIR).isDirectory()) {
    console.warn("[hooks] .git directory not found. Skipping hook installation.");
    process.exit(0);
  }
}

function ensureHooksDir() {
  fs.mkdirSync(HOOKS_DIR, { recursive: true });
}

function buildHookContent() {
  const cmds = [
    "lint",
    "test",
    "codex:validate-pack",
    "codex:validate-links",
    "codex:status"
  ];
  const prefix = "apps/keyboard-defense";
  const lines = [
    "#!/usr/bin/env bash",
    MARKER,
    "set -euo pipefail",
    "",
    'if [ "${SKIP_HOOKS:-}" = "1" ]; then',
    '  echo "[hooks] SKIP_HOOKS=1 detected. Skipping pre-commit checks."',
    "  exit 0",
    "fi",
    "",
    'REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"',
    'cd "$REPO_ROOT"',
    'echo "[hooks] Running Keyboard Defense pre-commit checks..."',
    ""
  ];
  for (const cmd of cmds) {
    lines.push(`npm run ${cmd} --prefix ${prefix}`);
  }
  lines.push('echo "[hooks] All checks passed."');
  lines.push("");
  return lines.join("\n");
}

function installHook() {
  const content = buildHookContent();
  if (fs.existsSync(HOOK_PATH)) {
    const existing = fs.readFileSync(HOOK_PATH, "utf8");
    if (!existing.includes(MARKER)) {
      console.warn(
        "[hooks] Existing pre-commit hook detected that was not generated by this script. Skipping overwrite."
      );
      return;
    }
  }
  fs.writeFileSync(HOOK_PATH, content, { mode: 0o755 });
  fs.chmodSync(HOOK_PATH, 0o755);
  console.log(`[hooks] Installed pre-commit hook at ${path.relative(REPO_ROOT, HOOK_PATH)}.`);
}

ensureGitRepo();
ensureHooksDir();
installHook();
