class_name SimIntents
extends RefCounted

const CommandKeywords = preload("res://sim/command_keywords.gd")
const RebindableActions = preload("res://game/rebindable_actions.gd")
static var COMMANDS: Array[String] = CommandKeywords.keywords()

static func make(kind: String, data: Dictionary = {}) -> Dictionary:
    var intent := {"kind": kind}
    for key in data.keys():
        intent[key] = data[key]
    return intent

static func help_lines() -> Array[String]:
    var bind_hint: String = RebindableActions.format_actions_hint()
    return [
        "Commands:",
        "  help - list commands",
        "  version - show game and engine versions",
        "  status - show phase and resources",
        "  gather <resource> <amount> - add resources (day only)",
        "  build <type> [x y] - place a building (day only)",
        "  build types: farm, lumber, quarry, wall, tower",
        "  explore - reveal a tile and gain loot (day only)",
        "  interact - interact with nearby point of interest (day only)",
        "  choice <id> - select an event choice",
        "  skip - skip the current event",
        "  upgrades [kingdom|unit] - show upgrade tree",
        "  buy <kingdom|unit> <id> - purchase an upgrade",
        "  cursor <x> <y> - move cursor",
        "  cursor <dir> [n] - move cursor up/down/left/right",
        "  inspect [x y] - inspect tile at cursor or coords",
        "  map - print ASCII map",
        "  demolish [x y] - remove a structure (day only)",
        "  preview <type|none> - toggle build preview",
        "  wait - advance a night step without a miss penalty (night only)",
        "  overlay path <on|off> - toggle path overlay",
        "  upgrade [x y] - upgrade a tower (day only)",
        "  enemies - list active enemies",
        "  report - toggle typing report panel",
        "  settings - toggle settings panel",
        "  settings show|hide - show or hide settings panel",
        "  settings lessons - show lessons prefs and health legend",
        "  settings prefs - show settings summary",
        "  settings scale [80|90|100|110|120|130|140|+|-|reset] - adjust UI scale (alias: settings font)",
        "  settings compact [on|off|toggle] - reduce panel verbosity",
        "  settings verify - print UI diagnostics",
        "  settings conflicts - print keybind conflicts only",
        "  settings resolve [apply] - auto-resolve keybind conflicts",
        "  settings export [save] - export keybind diagnostics as JSON",
        "  balance verify - run balance invariant checks",
        "  balance export [group] - export balance diagnostics as JSON",
        "  balance export save [group] - save balance diagnostics as JSON",
        "  balance diff [group] - compare balance diagnostics to saved baseline",
        "  balance summary [group] - print balance pacing summary (groups: wave, enemies, towers, buildings, midgame)",
        "  tutorial - toggle onboarding panel",
        "  tutorial restart - restart tutorial steps",
        "  tutorial skip - mark tutorial complete",
        "  bind <action> [key] - set a hotkey. %s" % bind_hint,
        "  bind <action> reset - restore default hotkey",
        "  history - toggle typing history panel",
        "  history clear - clear typing history",
        "  trend - toggle typing trend panel",
        "  goal - show practice goal and options",
        "  goal <balanced|accuracy|backspace|speed> - set practice goal",
        "  goal next - cycle practice goals",
        "  lesson - show lesson list",
        "  lesson <id> - set lesson (day/game_over only)",
        "  lesson next - cycle lessons (day/game_over only)",
        "  lesson prev - cycle lessons backward (day/game_over only)",
        "  lesson sample [n] - show sample words",
        "  lessons - toggle lesson panel",
        "  lessons reset [all] - reset lesson progress",
        "  lessons sort [default|recent|name] - sort lesson list",
        "  lessons sparkline [on|off] - toggle lesson sparklines",
        "  Hotkeys: see Settings -> Controls or use bind <action>.",
        "  end - finish day and begin night",
        "  seed <string> - set RNG seed",
        "  defend <text> - debug alias for night input",
        "  restart - restart after game over",
        "  save - write savegame.json",
        "  load - load savegame.json",
        "  new - start a new run",
        "  Economy guardrails apply midgame; see Settings -> Economy.",
        "Night:",
        "  Type an enemy word and press Enter",
        "Examples:",
        "  gather wood 10",
        "  build farm",
        "  build tower 9 5",
        "  explore",
        "  interact",
        "  choice a",
        "  cursor 8 5",
        "  cursor up 3",
        "  inspect",
        "  preview tower",
        "  wait",
        "  overlay path on",
        "  upgrade",
        "  enemies",
        "  goal",
        "  lesson",
        "  lesson sample 3",
        "  lessons",
        "  report",
        "  history",
        "  trend",
        "  tutorial",
        "  map",
        "  seed warmup-run",
        "Full command reference: docs/COMMAND_REFERENCE.md"
    ]
